services:
  - type: web
    name: checkin
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "3000"
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: "postgresql://postgres:JSYwi1rVH1NdXZNa@db.mvbeozeafscrwslvtoqw.supabase.co:5432/postgres"
      - key: DEDUP_IP_SALT
        generateValue: true
      - key: PUBLIC_BASE_URL
        sync: false
      - key: FEISHU_APP_ID
        sync: false
      - key: FEISHU_APP_SECRET
        sync: false
      - key: FEISHU_REDIRECT_URI
        sync: false
      - key: FEISHU_BITABLE_NAME
        value: 伙伴赋能培训签到信息表